lanugage: node_js
services:
  - docker
cache: npm
branches:
  only:
    - master
    - development
env:
  - DOCKER_COMPOSE_VERSION=1.25.5
before_install:
  - ./scripts/ci/before_install.sh
install:
  - npm i >> /dev/null
  - npx lerna bootstrap >> /dev/null
  - docker-compose pull >> /dev/null
script:
  - docker-compose build >> /dev/null
  - docker-compose up -d >> /dev/null
  - npm run build >> /dev/null
after_script:
  - npm t
