lanugage: node_js
services:
  - docker
cache: npm
before_install:
  - npm -g i npm@6.14.5
install:
  - npm i
  - npx lerna bootstrap
  - docker-compose pull
script:
  - docker-compose build && docker-compose up -d
  - npm run build
after_script:
  - npm t
