version: '3.7'
services:

  db:
    build: ./postgres
    container_name: tripsit_db
    restart: always
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - psql_data:/var/lib/postgresql/data

  web:
    container_name: tripsit_web
    build: ./nginx
    restart: always
    ports:
      - 8000:443/tcp
      - 8080:80/tcp
    extra_hosts:
      tripsit.local: 127.0.0.1
    volumes:
      - ./packages/web-main/docroot:/usr/share/nginx/tripsit_web
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d

  chat:
    container_name: tripsit_chat
    build: ./packages/chat
    restart: always
    ports:
      - 9000:9000/tcp
    extra_hosts:
      tripsit.local: 127.0.0.1
    volumes:
      - ./packages/chat/volume:/var/opt/thelounge

volumes:
  psql_data:
    name: tripsit_db_data
    driver: local
